### ISSUE TITLE
Download button format and file name (yaml instead of json)

### ISSUE THREAD

**Issue by AndreasA** [rohit-gohri/redocusaurus#10]
Currently the download button seems to provide the JSON file instead of the yaml file.

It would be nice if yaml could be used. Furthermore, specifying a filename would be great.

**Comment by rohit-gohri** [comment]
Currently the yaml is read during the build process, converted to JSON and passed to Redoc. If you want to pass the raw yaml, better to put it in the static folder and pass a URL to it in the plugin options.

**Comment by AndreasA** [comment]
@rohit-gohri OK, if I provide a specUrl it works as intended. However, how can I set the spec URL correctly in the `docusaurus.config.js` file as the hostname etc. is not yet defined and just using `/path/to/spec.yaml` does not work as it fails with an invalid URI error.

**Comment by rohit-gohri** [comment]
The recommended way by me would be to use the converted JSON as that is the fastest to load as no parsing needs to happen on client side.

If you want to allow downloading YAML and are okay with a little loading time, then put the the yaml in the static folder and pass the relative path in the `specUrl` option. Like here:

https://github.com/rohit-gohri/redocusaurus/blob/55649a0fff2dbc1e96b30290b922d4f04933e019/example/docusaurus.config.js#L18-L21

**Comment by rohit-gohri** [comment]
(after you update to the latest version, just released a patch which allows for relative paths in urls)

**Comment by AndreasA** [comment]
@rohit-gohri Thanks for adding support of this so fast.

So if I have a fix base URL, something like this `${BASE_URL}/path/to/static/openapi.yaml` would be fine.

At least it works locally. Haven't deployed it ye but should work there too.

**Comment by rohit-gohri** [comment]
> So if I have a fix base URL, something like this `${BASE_URL}/path/to/static/openapi.yaml` would be fine.

Yup, ideally I should be using the [useBaseUrl](https://docusaurus.io/docs/docusaurus-core#usebaseurl) hook in the Redoc component to automatically add it. But for now this works, maybe a fix for later.

**Comment by rogatec** [comment]
Just to be curious - the default name of the download file is `swagger.json` any chance to change the filename?
