### ISSUE TITLE
Integrate with existing documentation

### ISSUE THREAD

**Issue by janwirth** [rohit-gohri/redocusaurus#104]
Hey there,

I tried configuring redocusaurus as per installation instructions but it does not show up in the sidebar. What am I doing wrong?

I bootstrapped it with the classic template.
https://github.com/janwirth/redocusaurus-test

**Comment by rohit-gohri** [comment]
It doesn't really work as a sidebar item because it takes the full page. I usually add them to the nav bar as a dropdown

**Comment by rohit-gohri** [comment]
You can add a link to `/api` (default route, can change through config) in the nav bar

**Comment by janwirth** [comment]
Okay, I will try this and report back. Thanks!

**Comment by janwirth** [comment]
Thanks, I got it to work now. Awesome!
