### ISSUE TITLE
Hide right panel

### ISSUE THREAD

**Issue by liaocyintl** [rohit-gohri/redocusaurus#107]
Hi team.

The right panel is great but sometimes I want to hide it.
Do you have any idea?

I set redocOptions as follows:
```
theme: {
  primaryColor: '#1890ff',
  redocOptions: { // https://github.com/Redocly/redoc#redoc-options-object
    scrollYOffset: 60,
    theme: {
      rightPanel: {
        width: '0%',
        textColor: '#f00',
      }

```
but it doesn't work.

**Comment by rohit-gohri** [comment]
Will look into it, this should be doable.

**Comment by rohit-gohri** [comment]
This should be possible now that https://github.com/rohit-gohri/redocusaurus/pull/129 is merged

**Comment by rohit-gohri** [comment]
Closing this since theme options can now be specified https://redocusaurus.vercel.app/docs/getting-started/theme-options#theme-optional-object
