### ISSUE TITLE
Issues with rendering when hosted and interesting interaction when using raw.github url

### ISSUE THREAD

**Issue by jperk51** [rohit-gohri/redocusaurus#109]
Hi, 

I've been trying to use your tool to generate my docs for the last few days and a couple interesting things have come up. Firstly when I tried to reference my local spec I ran into the same issues others have with it being a multi-file spec, but when I reference the spec via its raw.github url using `specUrl` the doc was generated perfectly despite it being multiple files. 

Onto the real issue, when I have my spec referenced with `specUrl` and its raw.github url and I run my app locally everything works great, but when I host the app via github pages the spec is no longer able to render and I see these errors in the console. 

![image](https://user-images.githubusercontent.com/11302644/146245890-470cc119-6111-43ab-b4fe-2791fcb94907.png)

What's happening locally is exactly what we're looking for so any insights into what might be happening when it's hosted would be very much appreciated.

**Comment by rohit-gohri** [comment]
> via its raw.github url using specUrl the doc was generated perfectly despite it being multiple files.
That is interesting.

> the spec is no longer able to render and I see these errors in the console.
First time seeing this error. Is the app working in production mode too in local?

**Comment by jperk51** [comment]
>  Is the app working in production mode too in local?

When we run `yarn start` locally it works perfectly, but when we run `yarn build && yarn serve` then we see the issue. If you have any insights they would be very appreciated

**Comment by rohit-gohri** [comment]
Not sure if this is still a problem, but maybe the issue is a wrong `baseUrl` in the config?

**Comment by rohit-gohri** [comment]
Closing since no response. Feel free to reopen
