### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by AndreasA** [rohit-gohri/redocusaurus#11]
This plugin seems to fail if react 17 is installed. I know the dependencies also say it currently only supports 16 but it would be great if it would work with 17.

**Comment by rohit-gohri** [comment]
React support is dependent on https://github.com/redocly/redoc supporting it. Follow https://github.com/Redocly/redoc/issues/1518 for it, once they release support I'll publish a follow-up release.

**Comment by AndreasA** [comment]
Thanks for the feedback
