### ISSUE TITLE
Links to anchors do not properly reposition page

### ISSUE THREAD

**Issue by xgp** [rohit-gohri/redocusaurus#110]
I'm using the plugin to render API docs from a yaml spec file. The document renders correctly, but does not correctly reposition page when the anchor links are clicked in the left nav. You can see the bug here: https://phasetwo.io/api/
Source is here if you want to look: https://github.com/p2-inc/phasetwo-docs

**Comment by rohit-gohri** [comment]
Might be related to #66. I think you switched plugins, as I don't see any redoc API pages.

**Comment by xgp** [comment]
Thanks. I wasn't able to get it working right so I switched to another plugin.
