### ISSUE TITLE
Schema model imports not working for URL specs

### ISSUE THREAD

**Issue by aerovulpe** [rohit-gohri/redocusaurus#115]
When importing a Schema model into a MDX file for an Open API spec pointing to a URL like 

```
<ApiSchema id="using-spec-url" pointer="#/components/schemas/Pet" />
```

nothing is rendered.

I have been able to confirm this outside of my project on the official demo site:

https://rohit-gohri.github.io/redocusaurus/docs/guides/schema-imports#tag/store_model

![Screenshot 2022-01-22 160158](https://user-images.githubusercontent.com/6438457/150655450-94e7745e-6ebc-4d15-9df2-baa2360110ba.png)

**Comment by rohit-gohri** [comment]
I don't think they are supported with urls yet, I added the wrong config in the example 🤦 I'll fix it.  

Support could be added for urls (I have #80 open for it), but there is a problem that it render at build time so updating the content at the url will not update the example unless you rebuild the site

**Comment by rohit-gohri** [comment]
I have released a beta for v1 where this is fixed: https://github.com/rohit-gohri/redocusaurus/discussions/146

It has some breaking changes (mostly simplification of option names). New docs are at https://redocusaurus-v1.vercel.app/docs 

It will be great if you could try it and give some feedback.

**Comment by rohit-gohri** [comment]
It's working in v1: https://redocusaurus-v1.vercel.app/docs/guides/schema-imports 🥳

**Comment by aerovulpe** [comment]
This is awesome. 🎉 Thanks! I'll try it out 👍

**Comment by aerovulpe** [comment]
I just confirmed schema model imports work for URL specs in `1.0.0`. Thanks again @rohit-gohri! Great work you're doing with redocusaurus. 

![Screenshot 2022-03-17 132050](https://user-images.githubusercontent.com/6438457/158858554-326bb5bb-426c-4454-9fab-f7898fe37326.png)

**Comment by rohit-gohri** [comment]
Awesome! Just an FYI, the url schema is parsed and saved at build time so best to set up some kind of cron builds to to refresh it occasionally.

**Comment by pkvenu** [comment]
@rohit-gohri - Is there a working GitHub example I can look at for schema import?

**Comment by rohit-gohri** [comment]
@pkvenu The docs have an example:

Source Code:  https://github.com/rohit-gohri/redocusaurus/blob/main/website/docs/guides/schema-imports.mdx
Output: https://redocusaurus.vercel.app/docs/guides/schema-imports

If it doesn't work for you then please open a new issue
