### ISSUE TITLE
beta 2.0.15 - @theme/hooks/ was refactored. 

### ISSUE THREAD

**Issue by JohannesFerner** [rohit-gohri/redocusaurus#125]
When upgrading to `beta 2.0.15` the following issue is arising:

```
Module not found: Error: Can't resolve '@theme/hooks/useThemeContext' in '..../node_modules/redocusaurus/node_modules/docusaurus-theme-redoc/dist-jsx/theme/Redoc'
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```

Please see the breaking change here:
https://github.com/facebook/docusaurus/blob/main/CHANGELOG.md#boom-breaking-change
as well as here: 
> refactor: move @theme/hooks to @docusaurus/theme-common](https://github.com/facebook/docusaurus/pull/6289#)
https://github.com/facebook/docusaurus/pull/6289

**Comment by JohannesFerner** [comment]
```
import { useColorMode } from '@docusaurus/theme-common';
import { Redoc as RedocComponent, RedocStandalone, AppStore } from 'redoc';
import { RedocProps as Props, GlobalData } from '../../types/common';
import './styles.css';


/*!
 * Redocusaurus
 * https://rohit-gohri.github.io/redocusaurus/
 * (c) 2021 Rohit Gohri
 * Released under the MIT License
 */
function Redoc(props: Props): JSX.Element {
  const { isDarkTheme } = useColorMode();
  ```

**Comment by rohit-gohri** [comment]
It was published as 0.6.0, the pipeline failed but the it was released.

You can see published version: https://unpkg.com/browse/docusaurus-theme-redoc@0.6.0/src/theme/Redoc/Redoc.tsx

**Comment by rohit-gohri** [comment]
Upgrading to v0.6.0 should fix it, please reopen the issue if it doesn't.

**Comment by JohannesFerner** [comment]
Thanks solved.
