### ISSUE TITLE
Recent updates to `redocly/openapi-core` causing an error resolving `https-proxy-agent`

### ISSUE THREAD

**Issue by homotechsual** [rohit-gohri/redocusaurus#127]
See this upstream bug: https://github.com/Redocly/openapi-cli/issues/555

**Comment by homotechsual** [comment]
For now `npm i @redocly/openapi-cli@1.0.0-beta.81` resolves this.

**Comment by homotechsual** [comment]
Too soon - that just leads to `Can't resolve 'net'` and `Can't resolve 'tls'`

**Comment by rohit-gohri** [comment]
Thanks for reporting, I think I'll just pin redoc and openapi-cli to old versions for now.

**Comment by tatomyr** [comment]
Hi, the issue should've been resolved in the latest **openapi-cli** version (**1.0.0-beta.82**). Please check it out.

**Comment by homotechsual** [comment]
Can confirm as @tatomyr says - this is now resolved as it's automatically pulling `1.0.0-beta.82`

**Comment by rohit-gohri** [comment]
Closing then, thanks for pointing this out!
