### ISSUE TITLE
Dark theme - Third, fifth etc. sub-level wrong styling

### ISSUE THREAD

**Issue by AndreasA** [rohit-gohri/redocusaurus#13]
Not that big an issue but the styling for the third, fifth etc. levels is wrong in the dark theme.

**Comment by rohit-gohri** [comment]
Could you add a screenshot? I'm not sure I understand this completely.

**Comment by AndreasA** [comment]
@rohit-gohri Sure. will do so tomorrow (if I don't forget).

**Comment by AndreasA** [comment]
![image](https://user-images.githubusercontent.com/1383094/114659462-f5d07f00-9cf3-11eb-9be4-901fe2f18333.png)

**Comment by rohit-gohri** [comment]
Fixed in latest release.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/31949290/120068245-323a1d80-c09d-11eb-93b3-8ed2e81b68d3.png">

**Comment by AndreasA** [comment]
@rohit-gohri Thanks

**Comment by protyposis** [comment]
I am observing the same issue in v2.1.2 (with Docusaurus 3.5.2). 3rd level background and dropdown background (text barely visible) seem wrong. Screenshot and minimal OpenAPI spec attached.

![image](https://github.com/user-attachments/assets/fbeb159b-0de5-4a3b-86dd-9a7ea58f4a8d)
[openapi_sample.json](https://github.com/user-attachments/files/17458314/openapi_sample.json)

**Comment by rohit-gohri** [comment]
@protyposis please open a new issue
