### ISSUE TITLE
Excess whitespace below schema imports

### ISSUE THREAD

**Issue by Brookke** [rohit-gohri/redocusaurus#135]
Below each of the schema imports there is a lot of whitespace. Would there be any objection to me raising a PR to remove this whitespace? 

![Screenshot 2022-03-11 at 14 18 37](https://user-images.githubusercontent.com/10200358/157885157-25fccb7b-008e-4623-bd63-4c775a989c78.png)

**Comment by rohit-gohri** [comment]
> Would there be any objection to me raising a PR to remove this whitespace?

It would be much appreciated

**Comment by Brookke** [comment]
Awesome coming right up :)

**Comment by Brookke** [comment]
PR opened, first time doing the yarn changeset thing, so let me know if I have missed anything :)

**Comment by rohit-gohri** [comment]
Released with v0.9.1
