### ISSUE TITLE
Can't resolve 'fs' when trying to include specs

### ISSUE THREAD

**Issue by rubfergor** [rohit-gohri/redocusaurus#14]
I'm trying to compile a site after making some docs changes. It did work flawlessly, but when I try to build the site, I get the following errors:
```
/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib/resolve.js
Module not found: Can't resolve 'fs' in '/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib'/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib/utils.js
Module not found: Can't resolve 'fs' in '/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib'/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib/config/config.js
Module not found: Can't resolve 'fs' in '/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib/config'/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib/redocly/index.js
Module not found: Can't resolve 'fs' in '/Users/ruben/Git/app/node_modules/@redocly/openapi-core/lib/redocly'
```

For reference, I'm using:
```
    "@docusaurus/core": "~2.0.0-alpha.72",
    "@docusaurus/preset-classic": "~2.0.0-alpha.72",
    "redocusaurus": "~0.3.2"
```

And my Docusaurus.config.js redocusaurus field is:
```
    [
      'redocusaurus',
      {
        specs: [{
    spec: 'specs/api',
    routePath: path //this is an actual absolute path that I get with fs.resolve
}],
        theme: {
          primaryColor: '#f6b18f'
        }
      }
    ]
```
If I remove the plugin it does work, and if I try to put any other path or url in the "spec" field, I get the same error (I tried with the yaml provided in one of the examples and didn't work)

**Comment by rohit-gohri** [comment]
> And my Docusaurus.config.js redocusaurus field is:
> 
> ```
>     [
>       'redocusaurus',
>       {
>         specs: [{
>     spec: 'specs/api',
>     routePath: path //this is an actual absolute path that I get with fs.resolve
> }],

Just to be clear, `spec` here need to point to a OpenAPI yaml file and `routePath` is the route you want the docs to show up on the website, for eg. `/docs/api/v1/`.

You can see all the different option types in the example config: https://github.com/rohit-gohri/redocusaurus/blob/main/example/docusaurus.config.js

If the options are correct, would it be possible for you to share the open api file so I can test on local? You can also email me instead of making it public.

**Comment by rubfergor** [comment]
@rohit-gohri I can share a repro privately if you want, just let me know if it is ok to add you to the private repo I made so you can reproduce the issue (nothing really confidential as it is docs for a public API, but I prefer not to share it if I can avoid it just in case it breach some company privacy policy to share any kind of code)

**Comment by rohit-gohri** [comment]
That would be great

**Comment by rubfergor** [comment]
Done, let me know if I can help somehow!

**Comment by drichards-87** [comment]
@rohit-gohri Could you share what you did to fix this issue? I'm encountering the same error...

**Comment by rohit-gohri** [comment]
@drichards-87 I just upgraded redoc. If you are using webpack 5 then this might be the fix: https://github.com/Redocly/redoc/issues/1584#issuecomment-840559282

**Comment by maheshmnj** [comment]
Not sure who needs to see this, I spent couple of hours debugging the project and found that this issue was due to one of the imports in my docusaurus project 

`import siteConfig from '../../../docusaurus.config';` Removing this import fixed the issue

In my project, I was using `customFields` and imported `docusaurus.config.js` as below

```js
import siteConfig from '../../../docusaurus.config';

...
export default function FeaturedList(props) {
    var localPosts = siteConfig.customFields.allPosts;
```

and fixed it by using `useDocusaurusContext`

```js
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

....
export default function FeaturedList(props) {
    const { siteConfig } = useDocusaurusContext();
```
