### ISSUE TITLE
Anchors seem to be broken when using SchemaImports on a page

### ISSUE THREAD

**Issue by erodewald** [rohit-gohri/redocusaurus#157]
Hi, 

I'm experimenting with using your Docusaurus plugin (have not used it in any official capacities yet), and I am finding some quirks that would prevent me from using it in production docs. 

### Expected Behavior

Header anchors work as they typically do.

### Actual Behavior

A "rogue" anchor appears when scrolling to the end, or when using the right navigation anchors. I have attached a video. It doesn't _completely_ break functionality (i.e., navigating to a proper link anchor will take you to the right section), but it is very confusing to see something in URL that isn't related at all.

Pay close attention to the location bar, which suddenly begins showing `<url>#operation/sendSimulatedDiagnosticEvent`. As you might know, using `operations` isn't really a part of this plugin's functionality, so I'm surprised to see it. **For context**, that operation _does_ exist in the OpenAPI schema YAML, but it isn't explicitly referenced anywhere in my MDX file, nor any of its related schemas/responses. I'm not quite sure why _that_ would appear. 
 
https://user-images.githubusercontent.com/1534259/160298876-5111c8e2-4eb4-4a40-9a35-5cdb8a03b7d1.mov

This seems like a bug that is worth fixing, but I'm not particularly sure how to help you so let me know what you'd like to see.

**Comment by rohit-gohri** [comment]
Related to https://github.com/Redocly/redoc/issues/447

**Comment by rohit-gohri** [comment]
Fixed in v1.0.1 🎉

**Comment by erodewald** [comment]
Nice job 👏  Many thanks @rohit-gohri
