### ISSUE TITLE
Use of useColorMode().isDarkTheme is deprecated

### ISSUE THREAD

**Issue by erodewald** [rohit-gohri/redocusaurus#161]
While `isDarkTheme` was recently into `@docusaurus/theme-common` away from `useThemeContext()`, 12 days ago on Mar 18, it was deprecated entirely in favor of `useColorMode().colorMode === "dark"`.  

Usage found here: 
https://github.com/rohit-gohri/redocusaurus/blob/e81229325921eaa73d60f3914a14570721f583f7/packages/docusaurus-theme-redoc/src/utils/useSpec.ts#L20

As per: 
https://github.com/facebook/docusaurus/blob/bb55586c20a3477e04cedcc6b50bddadfac10431/packages/docusaurus-theme-common/src/contexts/colorMode.tsx#L127-L133

**Comment by rohit-gohri** [comment]
Fixed in [v1.0.3](https://github.com/rohit-gohri/redocusaurus/releases/tag/v1.0.3)

**Comment by EmaSuriano** [comment]
@rohit-gohri FYI I faced the same issue when updating to version `beta.21` of `docusaurus`. The solution I found temporaly is to keep the version to `beta.20` and everything work as expected 👍
