### ISSUE TITLE
The sidebar cannot be scrolled to the specified position after clicking

### ISSUE THREAD

**Issue by oil-oil** [rohit-gohri/redocusaurus#169]
I can't scroll to the specified API position when I click on the sidebar.

<img width="1955" alt="image" src="https://user-images.githubusercontent.com/57465570/164161926-c4b7d071-355f-4f3f-bd1e-02450da1d9fe.png">

The configuration file is as follows：
```
presets: [
    [
      "redocusaurus",
      {
        specs: [
          {
            spec: "https://api7-cloud-swagger.s3.amazonaws.com/swagger/cloud-console.json",
            route: "/api/",
          },
        ],
        theme: {
          primaryColor: '#e8433e',
        },
      },
    ],
```

redocusaurus version: 1.0.2

**Comment by oil-oil** [comment]
I checked the problem, when the `scroll-behavior: smooth` style is added it causes the scrolling to fail.

**Comment by rohit-gohri** [comment]
Might also be related to the code mentioned in #172
