### ISSUE TITLE
Sidebar not expanded on deeplinks

### ISSUE THREAD

**Issue by birkmose** [rohit-gohri/redocusaurus#173]
Example - navigating to the demo site: https://redocusaurus.vercel.app/examples/using-swagger-json/#operation/placeOrder

The sidebar does not expand as expected (it remains collapsed): 

![image](https://user-images.githubusercontent.com/3314191/166161049-ffda37dd-ad1d-4ff5-8897-209f8a712f99.png)

**Comment by rohit-gohri** [comment]
Might be the same issue as #172
