### ISSUE TITLE
redocusaurus fails the builds with beta.19 & .20

### ISSUE THREAD

**Issue by Licenser** [rohit-gohri/redocusaurus#175]
Hi,

it seems that using redocusaurus with beta.19 (or .20) causes the builds to fail on (probably) every page.

The build errors with:

```text
// ... snip ...

ERROR] Docusaurus server-side rendering could not render static page with path "/" (lots of those for different pages)

// ... snip ...

TypeError: content.replace is not a function (lots of those)

// ... snip ...

[ERROR] Error: Failed to compile with errors.
    at /home/heinz/tremor-www/node_modules/@docusaurus/core/lib/webpack/utils.js:182:24
    at /home/heinz/tremor-www/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/home/heinz/tremor-www/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Removing (or commenting) out the redocusauris preset solves the build problems:

```js
{
// ... snip ...

  presets: [
    // [
    //   'redocusaurus',
    //   /** @type {import('@docusaurus/preset-classic').Options} */
    //   ({
    //     // Plugin Options for loading OpenAPI files
    //     specs: [
    //       {
    //         spec: 'static/api/v0.12/openapi.yaml',
    //         route: '/api/',
    //       },
    //     ],
    //     // Theme Options for modifying how redoc renders them
    //     theme: {
    //       // Change with your site colors
    //       primaryColor: '#1890ff',
    //     },
    //   }),
    // ],
 
 // ... snip  ...
  ]
}
```

**Comment by Tricked-dev** [comment]
ran into the same issue while trying to build my website

**Comment by aerovulpe** [comment]
I think this is caused downstream from docusaurus.

https://github.com/facebook/docusaurus/issues/7398

**Comment by Licenser** [comment]
good insight!

**Comment by rohit-gohri** [comment]
Hey all! Thanks for reporting the issue. I'm trying to fix this currently

**Comment by rohit-gohri** [comment]
I would recommend downgrading to beta.18 till then.

**Comment by rohit-gohri** [comment]
On debugging, the issue seems to be originating in url validation in redoc which throws the error `TypeError [ERR_INVALID_URL]: Invalid URL` for relative paths now. If `chalk` was not found for some reason then it would not be able to print the error and report that error. I have pinned the `redoc` dependency to a specific version for now.

**Comment by rohit-gohri** [comment]
Fixed in [v1.0.3](https://github.com/rohit-gohri/redocusaurus/releases/tag/v1.0.3)

**Comment by ArthurFlageul** [comment]
Well done, thanks for the quick action @rohit-gohri 🙌

**Comment by shortcuts** [comment]
Thanks!
