### ISSUE TITLE
Issue runing Redocusaurus

### ISSUE THREAD

**Issue by anthony-sap** [rohit-gohri/redocusaurus#184]
Hi I've done a fresh install of Docusaurus and then followed the instructions for Redocusaurus and the system doesn't load 

![image](https://user-images.githubusercontent.com/12808283/170617864-ed8c9e63-5a68-4d75-b32d-908c2f3783ae.png)

Tyring preset config with this 
` presets: [
    [
      'redocusaurus',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            spec: './openapi/openapi.yaml',
            route: '/api/',
          },
        ],
        // Theme Options for modifying how redoc renders them
        theme: {
          // Change with your site colors
          primaryColor: '#1890ff',
        },
      }),
    ],
  ],`

or this 
` presets: [
    [
      'redocusaurus',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            spec: './openapi/openapi.yaml',
            route: '/api/',
          },
        ],
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
        },
        blog: {
          showReadingTime: true,
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],`

I get the same result. There are no errors in the npm console or the browser console

**Comment by rohit-gohri** [comment]
That is weird, is it possible for you to share the `openapi/openapi.yaml` file?

**Comment by anthony-sap** [comment]
It's happened with my own schema as well as the PetStore examples

`openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string`

**Comment by anthony-sap** [comment]
Do you need my build to test it? or it's replicatable

**Comment by anthony-sap** [comment]
HI Rohit, 
The default example works. I had my config completely wrong. I guess I didn't understand or realise that there was a redocusaurus object added to the main config. I think it's not clear enough in the documentation. 

I had just done this to the main config object
 `...
 presets: [
    [
      'redocusaurus',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            spec: './openapi/openapi.yaml',
            route: '/api/',
          },
        ],
        // Theme Options for modifying how redoc renders them
        theme: {
          // Change with your site colors
          primaryColor: '#1890ff',
        },
      }),
    ],
  ],
...`
