### ISSUE TITLE
Not support for non-latin heading anchors(slug)

### ISSUE THREAD

**Issue by natura4917** [rohit-gohri/redocusaurus#185]
The slug cannot return valid result when input is Unicode such as Korean, Japanese.. etc., so this occurs tag navigation and duplicate key error.

example... 
tag name => slug
주문 API => /#tag/API
상품 API => /#tag/API

**Comment by rohit-gohri** [comment]
Hi, this is handled by the redoc package. There is an open related issue for it already : https://github.com/Redocly/redoc/issues/1754

This preset just handles the integration of redoc with docusaurus, so I'm going to close this issue.
