### ISSUE TITLE
Ability to have theme options per spec

### ISSUE THREAD

**Issue by ArthurFlageul** [rohit-gohri/redocusaurus#186]
Hello, 

I'm using 2 specs on my website and I'd like one of these to _not_ display the full endpoint paths, and the last one to display it. 

Would it be possible to allow theme option per spec entry?

**Comment by rohit-gohri** [comment]
Maybe you can try having 2 instances of redocusaurus with different specs, paths, and theme options. See https://docusaurus.io/docs/using-plugins#multi-instance-plugins-and-plugin-ids

Not sure if it will work

**Comment by rohit-gohri** [comment]
I added some to handle multiple instances of presets with different ids. It should work in the next version.

**Comment by ArthurFlageul** [comment]
Wow, nice 😎  Thanks a lot 😊
