### ISSUE TITLE
Auto regenerate openapi remote config

### ISSUE THREAD

**Issue by baptisteArno** [rohit-gohri/redocusaurus#195]
Here is my test config:

```js
[
      'redocusaurus',
      {
        specs: [
          {
            spec: 'http://localhost:3001/api/doc',
            route: '/api/',
          },
        ],
      },
    ]
```

`http://localhost:3001/api/doc` serves the `openapi` config.

It works great on the initial page load.

But when I refresh the page, it doesn't reload the (updated) openapi config. I need to kill the app and restart `docusaurus start`.

Is it expected?

**Comment by rohit-gohri** [comment]
Yes, since docusaurus is a static site generator it will build the site at build time. But I guess for DX we can load it at runtime when using `start` rather than `build`
