### ISSUE TITLE
docusaurus build failed

### ISSUE THREAD

**Issue by guylev008** [rohit-gohri/redocusaurus#200]
Hi,
i'm using  "@docusaurus/core": "^2.0.0-beta.21", "@docusaurus/preset-classic": "^2.0.0-beta.21"
when i added redocusaurus 1.1.2 and tried to build the docs i got this error: 

![image](https://user-images.githubusercontent.com/39405738/173599778-4ea0c266-0724-4917-9ae6-318137df1c29.png)

this is the configuration:
` 
[
      'redocusaurus',
      {
        debug: true,
        specs: [
          {
            spec: 'https://redocly.github.io/redoc/openapi.yaml',
            route: '/api/',
          },
        ],
      }
    ],
`

**Comment by rohit-gohri** [comment]
@guylev008 Did this get fixed by the recent release (v1.2.0) or was due to some other reason?
