### ISSUE TITLE
hot reload for referenced files

### ISSUE THREAD

**Issue by mauris** [rohit-gohri/redocusaurus#213]
Please correct me if I'm wrong:

[OpenAPI 3.0 supports breaking down the main spec file into smaller files](https://swagger.io/docs/specification/using-ref/) through the use of `$ref`. In fact, Redoc supports the use of `$ref: ./intro.md` to import Markdown content into `description` fields. 

Docusaurus provides hot-reload through Webpack. In redocusaurus, this is implemented through [`docusaurus-plugin-redoc` where `getPathsToWatch()`](https://github.com/rohit-gohri/redocusaurus/blob/main/packages/docusaurus-plugin-redoc/src/index.ts) returns the absolute pathname to the spec file.

However, this only provides hot-reload to the main spec file, and not other referenced files.

I propose that we scan the refs and include them in the `getPathsToWatch()` so that hot reload can be properly implemented for referenced files loaded in Docusaurus.

**Comment by rohit-gohri** [comment]
Sounds like a good idea

**Comment by mauris** [comment]
instead of scanning the `$ref` tags, we could use the `fileDependencies` result from the `bundle()` function. neat.

**Comment by rohit-gohri** [comment]
Released in https://github.com/rohit-gohri/redocusaurus/releases/tag/v1.2.3
