### ISSUE TITLE
Links to anchors do not properly reposition page

### ISSUE THREAD

**Issue by OlaStenberg** [rohit-gohri/redocusaurus#214]
I noticed the same issue described on https://github.com/rohit-gohri/redocusaurus/issues/110

Can be reproduced at https://sushi-docs-rfv1c3av5-teamsushi.vercel.app/api/furo

If you'd like more context, here's the repo: https://github.com/sushiswap/sushi-docs
At the time of writing this is on a feature branch: [feature/redocusaurus-and-furo](https://github.com/sushiswap/sushi-docs/tree/feature/redocusaurus-and-furo)

**Comment by rohit-gohri** [comment]
That's strange, it works in the examples website. Can you try adding `operationId` to the openapi.yaml? I think giving them a unique id might make it work

**Comment by OlaStenberg** [comment]
Like this?
https://github.com/sushiswap/sushi-docs/commit/c600903ea45be88a11e9615b0d0416a5cda8a531

Good idea, but unfortunately it didn't make a difference:
https://sushi-docs-2cmtz9li9-teamsushi.vercel.app/api/furo

**Comment by isaiahdahl** [comment]
I was experiencing the same issue. For me it ended up being because I had `scroll-behavior: smooth;` on the body. took it off and it started working.

Checked your repo and see you have that CSS property as well. Try that!

**Comment by OlaStenberg** [comment]
> I was experiencing the same issue. For me it ended up being because I had `scroll-behavior: smooth;` on the body. took it off and it started working.
> 
> Checked your repo and see you have that CSS property as well. Try that!

Awesome, thanks, it worked!

**Comment by rohit-gohri** [comment]
Closing this since the issue was solved
