### ISSUE TITLE
Code samples in light mode have poor color contrast

### ISSUE THREAD

**Issue by aerovulpe** [rohit-gohri/redocusaurus#217]
Hi,

Thanks, @rohit-gohri for this awesome tool and being really helpful.

I have noticed an issue that I'm not sure is known. 

The light mode theme makes it hard to read the text inside code samples.

![image](https://user-images.githubusercontent.com/6438457/175341611-f867de8c-bf35-4147-9870-469133ddad48.png)

Thanks again for all your help.

**Comment by aerovulpe** [comment]
Looking at the CSS, this is caused by `background-color: var(--ifm-background-color);` when `--ifm-background-color` is a light color. Which makes sense for a light theme.

**Comment by kimsauce** [comment]
I am seeing this issue as well
<img width="655" alt="2022-07-06_16-42-49" src="https://user-images.githubusercontent.com/56411016/177660798-2fca3454-379f-4f25-887a-4976bf613dff.png">

**Comment by rohit-gohri** [comment]
Can you provide a openapi yaml that has code samples (even better would be a PR to add it to examples) ? So I can reproduce it

**Comment by aerovulpe** [comment]
Hey @rohit-gohri , the OpenAPI YAML specification used for the multi-file YAML example has code samples. 

I've created a commit replicating this in the example app by setting the `--ifm-background-color` theme variable to a light color for the light theme.

Here's the commit: https://github.com/ChatKitty/redocusaurus/commit/196523bb96f60aaf9a1cd210d40785325e0544bf

The screenshot is `/examples/using-multi-file-yaml/#tag/pet/operation/newPet` of the `website` example project running on that commit.

![image](https://user-images.githubusercontent.com/6438457/178144096-888e9a22-8a90-48ef-a6ac-59bf1f662128.png)

**Comment by rohit-gohri** [comment]
> the OpenAPI YAML specification used for the multi-file YAML example has code samples.

Thanks, forgot about this 🤦 

Can you test the fix by installing [redocusaurus@v0.0.0-test-20220711040249](https://www.npmjs.com/package/redocusaurus/v/0.0.0-test-20220711040249) ?

**Comment by aerovulpe** [comment]
Thanks, @rohit-gohri! 

I have installed [redocusaurus@v0.0.0-test-20220711040249](https://www.npmjs.com/package/redocusaurus/v/0.0.0-test-20220711040249) and confirmed that it fixes this. 👍

**Comment by rohit-gohri** [comment]
Released in https://github.com/rohit-gohri/redocusaurus/releases/tag/v1.2.3
