### ISSUE TITLE
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by pnispel** [rohit-gohri/redocusaurus#222]
same error as here: https://github.com/rohit-gohri/redocusaurus/issues/97

```
"dependencies": {
    "@docusaurus/core": "^2.0.0-beta.21",
    "@docusaurus/preset-classic": "^2.0.0-beta.21",
    "@mdx-js/react": "^1.6.22",
    "clsx": "^1.1.1",
    "prism-react-renderer": "^1.3.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "redocusaurus": "1.2.3"
  },
```

I think its related to this: https://github.com/eemeli/yaml/issues/208

regardless I was able to resolve it by 

```
"resolutions": {
    "yaml": "1.10.2"
  }
```

**Comment by rohit-gohri** [comment]
This looks like an issue in the yaml package (which is fixed now). And since it's not directly managed by redocusaurus I don't think we need to anything. Closing this for now, let me know if it is still an issue
