### ISSUE TITLE
Passing 'pagination' to redoc

### ISSUE THREAD

**Issue by doublex** [rohit-gohri/redocusaurus#225]
Question about migrating: `docusaurus-openapi` creates one HTML page for each API path.

The redocly-docs claim there is a pagination-feature:
https://redocly.com/docs/api-reference-docs/configuration/functionality

Howto pass options from redocusauros to redocly?

**Comment by rohit-gohri** [comment]
Is it a paid redocly feature or available in OSS cli? It will only work if in OSS. I tried testing it in #226 but could not get it to work

**Comment by doublex** [comment]
I have no idea (I could not get it to work either).
The docs do not mention a paid redocly feature.
Anyway - thanks a lot for your answer!

**Comment by rohit-gohri** [comment]
It is a paid feature. From their docs:

> The Redoc Community Edition (free and open source version) can only use the options marked as supported.

There is a text "Supported in Redoc CE." in settings supported in community edition. And pagination is not one of them. I think if we add the licenseKey in the redocly file it will work. But I don't have one to test it out.

**Comment by doublex** [comment]
Sorry for the inconvenience.

**Comment by rohit-gohri** [comment]
No problem :D
