### ISSUE TITLE
Updating redoc package to newest release candidate

### ISSUE THREAD

**Issue by Joe312341** [rohit-gohri/redocusaurus#227]
Hello,

First of all thank you for providing this package. Are there any plans to update the redoc version to the newest release candidate. There have been quite a few important bug fixes since rc.72 that would be useful to have access to.

Thank you!

**Comment by rohit-gohri** [comment]
Would be great if you (or someone) can open a PR. I'll be happy to merge it and release

**Comment by z-hirschtritt** [comment]
Looks like the non-rc 2.0 was just released 🎉 (https://github.com/Redocly/redoc/releases/tag/v2.0.0). I'll try and put up a PR this week for the updoot

**Comment by z-hirschtritt** [comment]
https://github.com/rohit-gohri/redocusaurus/pull/235

**Comment by z-hirschtritt** [comment]
✅ https://github.com/rohit-gohri/redocusaurus/pull/235

**Comment by rohit-gohri** [comment]
Released in 1.4.0. Thanks!
