### ISSUE TITLE
Dark Mode Auth Dropdown Caret cannot be seen

### ISSUE THREAD

**Issue by Snivio** [rohit-gohri/redocusaurus#233]
The Auth Dropdown Cannot be seen in the Dark Mode for both the states of toggle

![image](https://user-images.githubusercontent.com/31371104/189877895-82223aee-7a39-4776-a3d5-36d5fb4d8413.png)

Workaround:
```
[data-theme='dark'] .redocusaurus .api-content div h5 + svg polygon {
  filter: invert(1);
}
```

**Comment by Snivio** [comment]
PR:
https://github.com/rohit-gohri/redocusaurus/pull/234

**Comment by rohit-gohri** [comment]
released
