### ISSUE TITLE
Try it API console feature

### ISSUE THREAD

**Issue by Yuan1979** [rohit-gohri/redocusaurus#24]
Is it possible to have the try function like what we have in general apidoc/swagger?

**Comment by rohit-gohri** [comment]
Not sure what you are talking about, could you add an example?

**Comment by Yuan1979** [comment]
Hi, Rohit, 

What I mean is like the swagger ui, we have a "Try it out" button.

![image](https://user-images.githubusercontent.com/57373005/117278959-83ba0880-ae61-11eb-94bd-8c220c372a08.png)

Another question, is it possible to have the openapi.yaml in another folder, i.e. apis to handle multiple openapi files.

Btw, I love what you have done. Great work.

**Comment by Yuan1979** [comment]
Another issue, when i change the routePath to something other than api, i.e./api/petstore, i got another issue:

Error: end of the stream or a document separator is expected in "http://localhost:3000/api/openapi.yaml" at line 35, column 47:
    at BaseResolver.parseDocument (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:122:19)
    at eval (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:133:29)

**Comment by rohit-gohri** [comment]
> Hi, Rohit,
> 
> What I mean is like the swagger ui, we have a "Try it out" button.
> 

So this plugin is a wrapper around https://github.com/redocly/redoc to make it easy to use with docusaurus, so a feature like that will be out of scope for the purpose of this plugin.

They already have an open issue for this: https://github.com/Redocly/redoc/issues/53

**Comment by rohit-gohri** [comment]
> Another question, is it possible to have the openapi.yaml in another folder, i.e. apis to handle multiple openapi files.

Not sure what you mean. Some thing like #23 ?


> Btw, I love what you have done. Great work.

Thanks! :D

**Comment by rohit-gohri** [comment]
Closing this, since the original request is out of scope for this project. Hopefully redoc will implement it.

Please open a new issue for any other issues

**Comment by Anthony-Gaudino** [comment]
Hi @rohit-gohri 

There's a plugin for ReDoc to do this: https://github.com/wll8/redoc-try

Maybe it will work well and just need some styling.

I'm also interested on this.

**Comment by rohit-gohri** [comment]
@Anthony-Gaudino Styling wll8/redoc-try to also support docusaurus themes is going to be a lot of work. I think a better alternative is to use code examples (curl is one) instead that make it easy to try the API in your local, and they are already supported by redoc.

**Comment by Songkeys** [comment]
@rohit-gohri 

> I think a better alternative is to use code examples

Could you please instruct me to enable the code examples? I tried what the doc says but not working:

```js
        theme: {
          options:
            {
              // https://redocly.com/docs/api-reference-docs/configuration/functionality/
              hideTryItPanel: false,
              generateCodeSamples: {
                languages: [
                  { lang: "curl" },
                  { lang: "Node.js" },
                  { lang: "JavaScript", label: "JS" },
                ],
              },
            },
        },
```

Thank you in advance.

**Comment by rohit-gohri** [comment]
Hey @Songkeys, that feature is part of redocly's paid offerings. From their docs (https://redocly.com/docs/api-reference-docs/guides/generate-code-samples/) : 

> warning
> 
> Auto-generated code samples are not available in Redoc (the "community edition").

**Comment by Songkeys** [comment]
Oh. Btw, is `redocusaurus` compatible with the paid service? (I see I need to configure a `license` key to enable this?) If so, I will a deep look at their paid service.

**Comment by rohit-gohri** [comment]
I'm not sure, haven't used it. We use the official package behind the scenes: https://github.com/Redocly/redoc/
If that can be configured with `licenseKey` then so should `redocusaurus`

Btw, they also have a "Try it API console": https://redocly.com/docs/api-reference-docs/guides/try-it-console/

**Comment by Songkeys** [comment]
I'll take a look. Thank you so much for this info and this amazing project!

**Comment by uSkizzik** [comment]
> Hey @Songkeys, that feature is part of redocly's paid offerings. From their docs (https://redocly.com/docs/api-reference-docs/guides/generate-code-samples/) :

How much of a pain would it be to remake it 🤔

**Comment by rohit-gohri** [comment]
> How much of a pain would it be to remake it 🤔

Not in scope of this package. This package's aim is just to provide an integration, not to remake redoc.
