### ISSUE TITLE
Search doesn't work in Docusaurus 

### ISSUE THREAD

**Issue by moyicat** [rohit-gohri/redocusaurus#240]
Apologies if it's a known issue, but Redocly search doesn't work for me in docusaurus:

When I search for something that's suppose to work, no result is shown:
<img width="296" alt="Screen Shot 2022-09-26 at 10 01 20 PM" src="https://user-images.githubusercontent.com/2023450/192436137-8a486d37-5b54-4778-9529-22906f2d75eb.png">

However, it renders when there's no result:
<img width="306" alt="Screen Shot 2022-09-26 at 10 01 40 PM" src="https://user-images.githubusercontent.com/2023450/192436206-449258cb-2157-478a-b3a8-574b275ca2c0.png">

Meanwhile, if I run redocly with `openapi preview-docs --config=./api-specs/preview-config.yaml api-specs/openapi.yaml` the search does work:

<img width="260" alt="Screen Shot 2022-09-26 at 10 03 50 PM" src="https://user-images.githubusercontent.com/2023450/192436377-d1076ebf-b70d-47b8-bfdb-14e8628ab958.png">

**Comment by davidelettieri** [comment]
Check if there is a broken logo url

**Comment by moyicat** [comment]
> Check if there is a broken logo url

I'm not sure if I follow ... how's that relevant to search?

**Comment by davidelettieri** [comment]
For me search was not working and I had a broken logo url. Removing the logo from the open api spec fixed the issue
