### ISSUE TITLE
Route not allowed in Canary Build

### ISSUE THREAD

**Issue by ericpassmore** [rohit-gohri/redocusaurus#244]
Running some tests with Canary build of Docusaurus. This is working with Docusaurus 2.1.0 and Redocusaurus 1.4.0. When upgrading to unreleased preview versions get the following error.  

### Command 
`npm run build`

### Error
[ERROR] ValidationError: "route" is not allowed

### Versions
Docusaurus version: 0.0.0-5345
redocusaurus version: 0.5.0-next.0 
Node version: v16.15.1

### Config
```
    [
       'redocusaurus',
       {
         // Plugin Options for loading OpenAPI files
         specs: [
           {
             spec: 'openapi/leap-plugins/latest/test_control.swagger.yaml',
             route: '/leap-plugins/latest/test_control.api/',
           },
           {
             spec: 'openapi/leap-plugins/latest/trace_api.swagger.yaml',
             route: '/leap-plugins/latest/trace.api/',
           },
         ],
         // Theme Options for modifying how redoc renders them
         theme: {
           // Change with your site colors
           primaryColor: '#1890ff',
         },
       },
     ],
```

**Comment by rohit-gohri** [comment]
Should be fixed in latest version as we now use version 2.3.1
