### ISSUE TITLE
Build Failed after Upgrading Docusaurus from 2.1.0 to 2.2.0

### ISSUE THREAD

**Issue by HazyFish** [rohit-gohri/redocusaurus#247]
Build failed after upgrading Docusaurus from 2.1.0 to 2.2.0.
Using `redocusaurusn@1.4.0`.

### Error Message

```
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/software-engineering/models.
```

### MDX

```mdx
---
sidebar_position: 4
---

import ApiSchema from '@theme/ApiSchema';

<ApiSchema pointer="#/components/schemas/User" />

```

### Redocusaurus Config

```js
// Redocusaurus config
    [
      'redocusaurus',
      {
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            spec: 'api-specs/user-api-v3.yaml'
          },
        ],
        // Theme Options for modifying how redoc renders them
        theme: {
          // Change with your site colors
          primaryColor: '#1890ff',
        },
      },
    ],
```

**Comment by rohit-gohri** [comment]
If you can  add some more information (minimal reproduction) it'll be great

**Comment by HazyFish** [comment]
I was not able to reproduce the problem on a fresh project, but I encountered the same problem again in another repo.

There is also a similar issue I found on StackOverflow.
https://stackoverflow.com/questions/74179735/docusaurus-server-side-rendering-could-not-render-static-page-with-path

Is it possible to give you access to my private repo so you can take a look?

**Comment by HazyFish** [comment]
I solved the problem by adding `@docusaurus/types` and `@docusaurus/theme-common` to deps.

The root cause is the same as https://github.com/facebook/docusaurus/issues/6724

**Comment by rohit-gohri** [comment]
Thanks for posting the solution!
