### ISSUE TITLE
Theme options doesnt works with docusaurus 2.2.0

### ISSUE THREAD

**Issue by juanvargas-pax** [rohit-gohri/redocusaurus#248]
Im passing a theme options object to redocusaurus but doesnt work. 

**docusaurus.config.js**
```
presets: [
    [
      "@docusaurus/preset-classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
        },
        blog: {
          showReadingTime: true,
        },
        theme: {
          customCss: require.resolve("./src/css/custom.scss"),
        },
      }),
    ],
    [
      "redocusaurus",
      {
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            spec: "public/openapi.json",
            route: "/apiv2/",
          },
        ],
        debug: true,
        // Theme Options for modifying how redoc renders them
        theme: {
          codeBlock: {
            backgroundColor: "white",
          },
          rightPanel: {
            backgroundColor: "red",
            textColor: "#19282f",
          },
        },
      },
    ],
  ],
```

Screenshot: as you may see the right panel keeps the default background color
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/85582145/201950335-d00becaa-6728-491f-850b-cbb20d36217a.png">

**Package.json**
 "dependencies": {
    "@docusaurus/core": "2.2.0",
    "@docusaurus/preset-classic": "2.2.0",
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mdx-js/react": "^1.6.22",
    "buffer": "^6.0.2",
    "clsx": "^1.2.1",
    "core-js": "^3.25.5",
    "mobx": "^6.6.2",
    "prism-react-renderer": "^1.3.5",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "redocusaurus": "^1.4.0",
    "styled-components": "^5.3.6",
    "yaml": "^1.10.0"
  },

**Comment by rohit-gohri** [comment]
The theme field is nested: https://redocusaurus.vercel.app/docs/getting-started/theme-options#theme-optional-object

Can use the typescript interface (like you are doing for preset-classic) to get better suggestions in the editor:

```
      /** @type {import('redocusaurus').PresetOptions} */
      {
        // Plugin Options for loading OpenAPI files
        specs: [
          {
            spec: "public/openapi.json",
            route: "/apiv2/",
          },
        ],
        debug: true,
        // Theme Options for modifying how redoc renders them
        theme: {
          theme: {
            codeBlock: {
              backgroundColor: "white",
            },
            rightPanel: {
              backgroundColor: "red",
              textColor: "#19282f",
            },
          },
        },
      },
```
