### ISSUE TITLE
Using / for API reference

### ISSUE THREAD

**Issue by jrub** [rohit-gohri/redocusaurus#273]
Hi there,

I'm using '/' as route on the config so that the main page is the API Reference (the Redoc component). However, no matter if I use the cusom page or custom layout, I get stuck into "Loading".

When using a different route like '/api', it works fine.

Any clue? Thx!

**Comment by rohit-gohri** [comment]
Are using both the `route` option and also creating a custom page using index.jsx/tsx file in the `pages` directory? Then these options might conflict, you can remove one of them and I think it should work. 

If you have a link to the repo that would be great to debug this

**Comment by jrub** [comment]
With `route` is completely removed from the config, and using https://github.com/rohit-gohri/redocusaurus/blob/main/website/src/pages/examples/custom-layout/index.jsx as my only src/pages/index , it's stuck on Loading.

However, now I tried to remove all the /src and using `route: '/'` on config and it loads fine.

Could it be that `import useSpecData from '@theme/useSpecData';` does not load at all?

**Comment by jrub** [comment]
@rohit-gohri here you have an example config and page https://github.com/jrub/redocusaurus_test

**Comment by rohit-gohri** [comment]
Figured it out. The id in `useSpecData` is supposed to be the same id you specify in the docusaurus config (here https://github.com/jrub/redocusaurus_test/blob/63a8e30710d18c586e835ff3d41047f450091a2b/docusaurus.config.js#L66). Let me know if this is not the fix.


I guess it's not very clear in the docs. Added it as a TODO to the existing docs ticket (https://github.com/rohit-gohri/redocusaurus/issues/147).

**Comment by jrub** [comment]
Cool! That worked, thank you 🙏
