### ISSUE TITLE
"Page not found" shows when loading operationId URL

### ISSUE THREAD

**Issue by jrub** [rohit-gohri/redocusaurus#282]
Hi there,

when loading an operationId by URL directly, a _"Page Not Found"_ is shown for an instant. You can check that behaviour here https://developers.quaderno.io/api/#tag/Invoices/operation/createInvoice 

Not sure if this comes from Redocusaurus, Redoc, or Docusaurus 🙏

**Comment by jrub** [comment]
For more info, I'm using the "Custom Page" way, like in:

```jsx
import React from 'react';
import Layout from '@theme/Layout';
import Redoc from '@theme/Redoc';
import useSpecData from '@theme/useSpecData';

function CustomPage() {
  const specData = useSpecData('openapi');
  return (
    <Layout
      title="..."
      description="..."
    >
      <Redoc {...specData} />
    </Layout>
  );
}

export default CustomPage;
```

**Comment by jrub** [comment]
Also, all crawlers are getting 404 so this is bad for SEO :-/

**Comment by rohit-gohri** [comment]
> all crawlers are getting 404 so this is bad for SEO :-/

that sucks 😕 

I see that the link now works without JS and returns 200 in the network tab, did you find a solution to this?

**Comment by jrub** [comment]
Yes! The key is that Gh-pages need `trailingSlash` to true, or the 404 will
happen

**Comment by rohit-gohri** [comment]
Cool, closing this then. Thanks for sharing
