### ISSUE TITLE
v1.6.1 Compresses Mobile View

### ISSUE THREAD

**Issue by shawnsull3** [rohit-gohri/redocusaurus#287]
Using Docusaurus v2.4.0 and Redocusaurus v1.6.1 the mobile view is compressed. The bug only appears when built. Running the site locally with `yarn start` the mobile view is fine. 

Screenshot of the mobile view and the CSS causing it:
![image](https://user-images.githubusercontent.com/58274573/232568611-958a1948-572f-4df0-9231-44c4c3fa5fd5.png)

It appears that the CSS that's causing the issue is overwriting the `width: 100%` from the index file.

This bug is affecting most of the sites found on the [who's using Redocusaurus page](https://rohit-gohri.github.io/redocusaurus/docs/who-is-using-redocusaurus) as well as the [Redocusaurus examples](https://rohit-gohri.github.io/redocusaurus/examples/using-single-yaml/)
![image](https://user-images.githubusercontent.com/58274573/232572653-652a0af4-a14c-4f3c-b615-a595dba66dbb.png)
![image](https://user-images.githubusercontent.com/58274573/232573586-0d554efb-8e1c-47e9-885b-9e4e4f48ef16.png)

Change log from v1.6.0 to v1.6.1: https://github.com/rohit-gohri/redocusaurus/compare/v1.6.0...v1.6.1

**Reverting to Redocusaurus v1.6.0 fixes the issue.**

**Comment by rohit-gohri** [comment]
Can confirm #276 introduced the regression. I'll revert it for now

**Comment by rohit-gohri** [comment]
Thanks for reporting, release 1.6.2 is out now

**Comment by shawnsull3** [comment]
@rohit-gohri No problem - thanks for the fix! 

I tried looking into why the changes in 1.6.1 were causing this regression but I couldn't quite figure it out.
