### ISSUE TITLE
docusaurus and redocusaurus version compatibility 

### ISSUE THREAD

**Issue by DckcDan** [rohit-gohri/redocusaurus#290]
Hi Rohi, thanks for this great plugin.
I am having difficulties getting it working due to some version incompatibilities.

Could you confirm what version of redocusaurus and   docusaurus/core are compatibles?

Thanks

**Comment by rohit-gohri** [comment]
It's tested with version `2.3.1` in the docs website. I don't think there should be any problems with later versions, we had a lot of issues during the beta versions but the docusaurus API is pretty stable now.

**Comment by DckcDan** [comment]
Thanks so much. I got it working with 2.3.1
