### ISSUE TITLE
CSS broken

### ISSUE THREAD

**Issue by Zenahr** [rohit-gohri/redocusaurus#305]
Sometimes its fine on deployment, sometimes not.

![image](https://github.com/rohit-gohri/redocusaurus/assets/47085752/b2ff5206-c625-4c97-af03-e319a8ae2b52)

Why would this happen?

**Comment by rohit-gohri** [comment]
This is related to this issue - https://github.com/rohit-gohri/redocusaurus/issues/215

There is currently no clear fix for this, you can follow the history of this in the original thread. I'll close this as duplicate
