### ISSUE TITLE
Is there a way to run the APIs through the redoc component ?

### ISSUE THREAD

**Issue by AnimeshRy** [rohit-gohri/redocusaurus#311]
I really liked the project and used it for an internal project. Is there a way to run the API calls with required params which lets users test the API on the website directly instead of us redirecting them to a postman collection ?

**Comment by rohit-gohri** [comment]
This plugin is a wrapper around [redocly/redoc](https://github.com/redocly/redoc) to make it easy to use with docusaurus, so a feature like that will be out of scope for the purpose of this plugin.

Redoc supports this in it's paid offerings only. They already have an open issue for this: https://github.com/Redocly/redoc/issues/53

Duplicate of #24
