### ISSUE TITLE
Support for Docusaurus 3.0

### ISSUE THREAD

**Issue by mt89vein** [rohit-gohri/redocusaurus#313]
Docusaurus yesterday released 3.0 which includes support for react 18. I tried to upgrade, but I see that I get peer dependency warnings for this plugin.

Do you plan to release an update which will support docusuarus 3?

**Comment by rohit-gohri** [comment]
Happy to accept any PRs that update the dependencies and peer dependencies. I personally will not be able to work on it for some time.

**Comment by zabomate** [comment]
@rohit-gohri please take a look at #314

**Comment by rohit-gohri** [comment]
Can someone install this test version - [v0.0.0-test-20231104142351](https://www.npmjs.com/package/redocusaurus/v/0.0.0-test-20231104142351) and confirm if everything works?

**Comment by zabomate** [comment]
@rohit-gohri I have tested and it works fine for me with the test package.

**Comment by rohit-gohri** [comment]
Thanks @zabomate ! Released as v2.0.0

**Comment by jwitz** [comment]
@zabomate Did you test with specs in external URLs? When I upgraded to 2.0.0, our remote specs broke (local refs worked fine).

After upgrading, I receive the same errors as in https://github.com/rohit-gohri/redocusaurus/issues/299

**Comment by rohit-gohri** [comment]
@jwitz I do have a test and it is deployed - https://redocusaurus.vercel.app/examples/using-remote-url/

**Comment by jwitz** [comment]
Thanks for the response @rohit-gohri When I plugged in the pet store spec into our site it worked, but when I used https://api.astronomer.io/spec/platform/v1beta1 it threw the error. It looks like something in our spec might not be formatted properly, I will investigate an open a docs PR if our issue might be encountered by other developers

**Comment by a-x-** [comment]
update package.json#description please
https://github.com/rohit-gohri/redocusaurus/blob/406fd2e8664edd8c92bffe5e2dc1c2d759236913/package.json#L4
