### ISSUE TITLE
Standalone redoc plugin

### ISSUE THREAD

**Issue by gituserjava** [rohit-gohri/redocusaurus#362]
Is there a way to just run "Docusaurus Plugin Redoc" standalone instead of setting up docusaurus? I am just looking for a tool to convert open api yaml file into mark down file and I need the source of the mark down file for other processing. Could you please let me know?

With the approach documented on "Getting Started/Installation" page I am able to get the final markdown UI, but I also need the source of the generated markdown file.

**Comment by rohit-gohri** [comment]
I don't think that's possible, it's out of scope for this project as it relies on a lot of docusaurus APIs

**Comment by gituserjava** [comment]
Ok, is there a way to just have the source of the html file that gets created? I can then use other tools to convert html to markdown.
