### ISSUE TITLE
Support proper Server Side Rendering

### ISSUE THREAD

**Issue by rohit-gohri** [rohit-gohri/redocusaurus#42]
Currently the server build only has a loading spinner. Checkout how redoc-cli generates server build: https://github.com/Redocly/redoc/tree/master/cli and see if it can be supported here.

**Comment by rohit-gohri** [comment]
This might be currently blocked by https://github.com/facebook/docusaurus/issues/3236

**Comment by monken** [comment]
Thanks for this! It works great except that it doesn't seem to include any stylesheets. When I disable JavaScript in the browser, the documentation doesn't render properly, and causes a flicker because the CSS eventually loads through JavaScript (I assume).

**Comment by rohit-gohri** [comment]
@monken Did you also add this: https://github.com/rohit-gohri/redocusaurus/discussions/88#discussioncomment-1307475 to the theme/Root component?

**Comment by monken** [comment]
This it it! Thank you!
