### ISSUE TITLE
Import single model defenition inside mdx files.

### ISSUE THREAD

**Issue by hleb-albau** [rohit-gohri/redocusaurus#46]
Is it possible to import a single model definition inside .mdx file?  I want to have raw /api/ ReDoc endpoint, but also use openapi models inside main documentation. Thanks

**Comment by rohit-gohri** [comment]
That would be pretty cool, redoc does expose `SchemaDefinition` component directly. Will see if it is possible.

**Comment by rohit-gohri** [comment]
Something like this?

```tsx
import ApiSchema from '@theme/ApiSchema';

<ApiSchema
  schemaRef="#/components/schemas/Pet"
/>
```

![image](https://user-images.githubusercontent.com/31949290/131202818-2b2e9b47-67af-4d81-904b-42d9a0c9f1e7.png)

**Comment by rohit-gohri** [comment]
With only schema and example hidden

![image](https://user-images.githubusercontent.com/31949290/131212552-76f0ca4a-7a5b-4796-a380-59fa99fe4636.png)
