### ISSUE TITLE
some markdown features work strange

### ISSUE THREAD

**Issue by mayneyao** [rohit-gohri/redocusaurus#48]
It seems that `<SecurityDefinitions />` works fine, but [pullright](https://redoc.ly/docs/api-reference-docs/embedded-markdown/#pull-right) is wrong , it should appear in the right pane.
```markdown
# Tutorial (displayed in the left navigation)

<PullRight>
This part will appear in the right pane.
</PullRight>

This part is in the body.  Lorem ipsum dolor!

<SecurityDefinitions />
```
![image](https://user-images.githubusercontent.com/6588202/119308534-bfe1cb80-bc9f-11eb-8666-8b5000b2cdf3.png)

https://redoc.ly/docs/api-reference-docs/embedded-markdown/

**Comment by rohit-gohri** [comment]
And it works in plain old Redoc? Only a problem in Docusaurus version?

**Comment by mayneyao** [comment]
My bad, it only works in redoc.ly's sass service. There is no code about `PullRight` in the open source version😂

https://github.com/search?q=org%3ARedocly+PullRight
