### ISSUE TITLE
CSS not specific enough

### ISSUE THREAD

**Issue by ArtFlag** [rohit-gohri/redocusaurus#59]
Hello,

These lines do not apply to docusaurus' components but to all the H3s and it's impacting other pages in my docs 🙃 

https://github.com/rohit-gohri/redocusaurus/blob/269ff70a263c96b9b5fc119b89fdc516fdf343ba/packages/docusaurus-theme-redoc/src/theme/Redoc/styles.css#L8

**Comment by rohit-gohri** [comment]
Released in 0.4.3
