### ISSUE TITLE
Enabling additional languages for syntax highlighting in Docusaurus breaks Redocusaurus

### ISSUE THREAD

**Issue by inacho** [rohit-gohri/redocusaurus#68]
### How to reproduce

Add additional languages for the syntax highlighting in Docusarus (https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages)

Example:

```javascript
module.exports = {
  // ...
  themeConfig: {
    prism: {
      additionalLanguages: ['java'],
    },
    // ...
  },
};
```

The additional language is correctly enabled in Docusaurus, however, when navigating to a Redocusaurus page the following error is happening:

`Uncaught (in promise) TypeError: lang is undefined`

![Screen Shot 2021-07-08 at 13 00 42](https://user-images.githubusercontent.com/742624/124860442-a0eb8e80-dfec-11eb-97e3-0291d9fabf0a.png)

### Dependencies used in package.json

```
"dependencies": {
    "@docusaurus/core": "2.0.0-beta.3",
    "@docusaurus/preset-classic": "2.0.0-beta.3",
    "@mdx-js/react": "^1.6.22",
    "@svgr/webpack": "^5.5.0",
    "clsx": "^1.1.1",
    "core-js": "^3.9.1",
    "docusaurus-theme-redoc": "^0.4.4",
    "file-loader": "^6.2.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "redoc": "^2.0.0-rc.54",
    "redocusaurus": "^0.4.4",
    "remark-mermaid-dataurl": "^1.0.1",
    "url-loader": "^4.1.1"
  },
```

Any idea of how to fix it?
Thanks

**Comment by rohit-gohri** [comment]
Redoc also [ships prism with itself](https://github.com/Redocly/redoc/blob/master/src/utils/highlight.ts), the global configs might be conflicting.

**Comment by inacho** [comment]
I noticed that the problem disappear if I add the language "scala" on top of "java":

```javascript
module.exports = {
  // ...
  themeConfig: {
    prism: {
      additionalLanguages: ['java', 'scala'],
    },
    // ...
  },
};
```

As you said, this is probably due to conflicts with prism in Redoc.
I guess Redoc expects to have Scala enabled.
Feel free to close the bug.

Thanks

**Comment by rohit-gohri** [comment]
Thanks for posting the solution 👍
