### ISSUE TITLE
Dark mode text theme

### ISSUE THREAD

**Issue by akinncar** [rohit-gohri/redocusaurus#8]
I created a simple example and called my api docs specs, but when I try to view the full URL with dark mode in the right session (with responses and payloads), I get a lighter text in dark mode, similar to background color

![image](https://user-images.githubusercontent.com/42688281/112505418-8528e900-8d6b-11eb-95a7-9219a203c3ee.png)

When I turn on light mode, this text color has fixed

![image](https://user-images.githubusercontent.com/42688281/112505721-cfaa6580-8d6b-11eb-9119-c766de5e0a1b.png)

**Comment by rohit-gohri** [comment]
It seems to be working in the example repo: https://rohit-gohri.github.io/redocusaurus/custom-layout/#tag/pet

Do you have any other css that might conflict with this?

**Comment by akinncar** [comment]
I tried in the same project with this pet yaml and works fine.

In my case, I use a json generated by JSDOC when I get this color problem, you can see the example [here](https://github-stars-api-akinncar.herokuapp.com/api-docs) where I have the problem.

By the way I validate my JSON with https://editor.swagger.io/ and seems OK, do you have any suggestion to do this working? I can't think in nothing until now.

**Comment by rohit-gohri** [comment]
Could also be a environment issue? Which browser/OS/etc are you running?

**Comment by qin-guan** [comment]
The styling will only work if the part of the docs uses [`operation`](https://github.com/rohit-gohri/redocusaurus/blob/main/packages/docusaurus-theme-redoc/src/theme/Redoc/styles.css#L53), if `[id^="operation"]` is removed it should apply styling to all of the items. If u take a look at the URL, it contains `#operation` https://rohit-gohri.github.io/redocusaurus/custom-layout/#operation/addPet as well.

**Comment by rohit-gohri** [comment]
Should be fixed in v0.3.3
