### ISSUE TITLE
Issue with collapsing code blocks

### ISSUE THREAD

**Issue by drichards-87** [rohit-gohri/redocusaurus#89]
I'm encountering an issue where multi-line code blocks are collapsing into a single line (in Docusaurus articles). I believe this could have something to do with Redocusaurus (not 100% sure though). Or rather, an issue with Redoc specifically.

This issue in the Docusarusus repo is identical to the issue I'm facing: https://github.com/facebook/docusaurus/issues/5443

If you go the URL mentioned in the issue (https://docs.talon.one/docs/dev/getting-started/overview/), scroll down to the first code block, and then hover over the Integration API or Management API link, the code block collapses into a single line.

Notice that this doesn't happen when hovering over any of the other navbar links.

Any insight would be appreciated as this is a real head scratcher for me.

**Comment by rohit-gohri** [comment]
I don't think this could be because of redoc, but I'll try to reproduce in my repo.

**Comment by drichards-87** [comment]
I appreciate it. I did notice this same issue occurring on another site that uses Redocusaurus: https://docs.spectacles.dev/app/tutorials/getting-started/

If you expand Reference in the left TOC and hover over API, the code block on the page collapses into a single line. (You may have to refresh the page in order to reproduce - it doesn't always happen consistently.)

**Comment by drichards-87** [comment]
@ygerg Do you have any guidance as to where/how to set this in our Docusaurus sites?
