### ISSUE TITLE
Can't resolve '@theme/hooks/useThemeContext'

### ISSUE THREAD

**Issue by thulasi-ram** [rohit-gohri/redocusaurus#96]
Docusaurus - ~2.0.0-beta.7~ **2.0.0-beta.6**

Module not found: Error: Can't resolve '@theme/hooks/useThemeContext' in '..../docusaurus-pipeline-v2/node_modules/docusaurus-theme-redoc/dist-jsx/theme/Redoc'

Could it be because of this change: https://github.com/facebook/docusaurus/pull/2934/files

**Comment by rohit-gohri** [comment]
Definitely because of that change

**Comment by rohit-gohri** [comment]
I tried to fix this but can't seem to find beta.7. [Releases page](https://github.com/facebook/docusaurus/releases) only lists beta.6 as the latest version

**Comment by thulasi-ram** [comment]
Apologies, it seems to happen on beta6 only.

**Comment by kago-dk** [comment]
Any hints on how to resolve it?

**Comment by radsmine** [comment]
@thulasi-ram How did you solve that issue? Facing the same issue even after downgrading. Please help, this is kinda urgent!
